# Generated by Django 4.1.5 on 2024-01-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('diet', models.BooleanField(default=True, verbose_name='Veg/Non-veg')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weight')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('body_type', models.TextField(blank=True, null=True, verbose_name='Body Type')),
                ('nutrition_predict', models.TextField(blank=True, null=True, verbose_name='Diet Prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
